export const DENTISTAS_PERMITIDOS = {
  CENTRO: {
    "LIMPEZA | RESTAURAÇÃO E CONSULTA INICIAL": [
      "LARYSSA SILVA DE QUEIROZ - CENTRO",
      "ADRIELY ABIGAIL SILVA FEITOSA - CENTRO",
      "ANA BEATRIZ ARRUDA DE SOUZA - CENTRO",
      "ANNA ELLYSE GRANT DE OLIVEIRA - CENTRO",
      "BRENDA HENRIQUE BEZERRA DA SILVA - CENTRO",
      "JACSANDRO CRUZ DE PAULA - CENTRO",
      "JUCYANNA SOUTO DE OLIVEIRA COSTA - CENTRO",
      "MARIA EUNICE FERREIRA DE QUEIROZ FELIX EIRELI - CENTRO",
      //"NATHALIA CRISTINA CAMARAO FERREIRA - CENTRO",
    ],

    ORTODONTIA: [
      "ADREILDO NEVES DE ALMEIDA SANTOS - CENTRO",
      "CAIO DE A COSTA EIRELI - CENTRO",
      "CLOALDO SANTOS SOARES MENDONCA - CENTRO",
      "JACKSON NEVES GOMES - CENTRO",
      "JADSON SILVESTRE DA SILVA - CENTRO",
      "MARIA EUNICE - ORTODONTIA - CENTRO",
      "NATALIA APARECIDA DE MEDEIROS VALENTIM - CENTRO",
      "ORTHO FACIAL LTDA - CENTRO",
      "ROBERTA GUIMARÃES RIHAN - CENTRO",
    ],

    ODONTOPEDIATRIA: [
      "CLAUDIA RODRIGUES PEREIRA DE ALMEIDA SOEIRO - CENTRO",
    ],

    PERIODONTIA: [
      "BARBARA FERNANDA N DA SILVA EIRELI - CENTRO",
    ],

    /*CIRURGIA: [
      "BRUNO ALEXANDER VALE DE ARAÚJO - CENTRO",
    ],*/

    RECONSTRUÇÃO: [
      "LARYSSA QUEIROZ - (RECONSTRUÇÃO)",
      "ANA BEATRIZ NEGREIROS SOARES DE MACEDO - CENTRO",
    ],
  },

  GOIANINHA: {
    "LIMPEZA | RESTAURAÇÃO E CONSULTA INICIAL": [
      "ADRIELLE NAYARA CARVALHO DA SILVA - GOIANINHA",
      "KARLA THAINA ALVES DA SILVA - GOIANINHA",
      "NATHALIA CRISTINA CAMARAO FERREIRA - GOIANINHA",
      "STEPHANNY INGRID MOURA FERREIRA - GOIANINHA",
      "VIVIANNE CRISTINA DE MEDEIROS LOURENÇO - GOIANINHA",
    ],

    ORTODONTIA: [
      "CAIO DE A COSTA EIRELI - ME - GOIANINHA",
      "DAYSE BEZERRA BEVENUTO - GOIANINHA",
      "DEBORA ANDRADE BARBOSA - GOIANINHA",
      "MARILIA MATOS DE OLIVEIRA - GOIANINHA",
    ],

    "CANAL | ENDODONTIA": [
      "ADRIELLE NAYARA CARVALHO (CANAL) - GOIANINHA",
    ],
  },

  "SANTA CRUZ": {
    "LIMPEZA | RESTAURAÇÃO E CONSULTA INICIAL": [
      "JULIA BARBARA MEDEIROS GALVAO - SANTA CRUZ",
      "KARLA VANESSA BEZERRA FERREIRA - SANTA CRUZ",
      "LARISSA LIMA TEIXEIRA - SANTA CRUZ",
      "RICENA ARITANA PEREIRA - SANTA CRUZ",
      "SANDRA MARINA GOMES RODRIGUES - SANTA CRUZ",
      "WALLESKA MINNELY MENDES PAIXÃO - SANTA CRUZ",
    ],

    ORTODONTIA: [
      "ANA LUIZA FERNANDES DE ALMEIDA - SANTA CRUZ",
      "MICHELE MIKAELA OLIVEIRA PONTES - SANTA CRUZ",
    ],

    RECONSTRUÇÃO: [
      "KARLA VANESSA BEZERRA FERREIRA (RECONSTRUÇÃO) - SANTA CRUZ",
    ],

    CIRURGIA: [
      "KARLA VANESSA BEZERRA FERREIRA (CIRURGIA) - SANTA CRUZ",
    ],

    "CANAL | ENDODONTIA": [
      "WALLESKA MINNELY MENDES PAIXÃO (CANAL) - SANTA CRUZ",
    ],

  ODONTOPEDIATRIA: [
      "RICENA ARITANA PEREIRA - SANTA CRUZ",
      "SANDRA MARINA GOMES RODRIGUES - SANTA CRUZ",
    ],

  },

  PARNAMIRIM: {
    "LIMPEZA | RESTAURAÇÃO E CONSULTA INICIAL": [
      "AL ODONTOLOGIA ESTETICA - PARNAMIRIM",
      "BRENDA HENRIQUE BEZERRA DA SILVA - PARNAMIRIM",
      "GABRIELA DE LIMA SILVA - PARNAMIRIM",
      "IZABELLA MOREIRA CORREA - PARNAMIRIM",
      "MATEUS GUEDES CARVALHO - PARNAMIRIM",
    ],

    ORTODONTIA: [
      "CAIO DE A COSTA EIRELI - ME - PARNAMIRIM",
      "NATALIA APARECIDA DE MEDEIROS VALENTIM - PARNAMIRIM",
      "ORTHO FACIAL LTDA - PARNAMIRIM",
      "ROBERTA GUIMARÃES RIHAN - PARNAMIRIM",
    ],

    ODONTOPEDIATRIA: [
      "CLAUDIA RODRIGUES PEREIRA DE ALMEIDA SOEIRO - PARNAMIRIM",
    ],

    PERIODONTIA: [
      "BARBARA FERNANDA N DA SILVA EIRELI - PARNAMIRIM",
    ],

    CIRURGIA: [
      "BRUNO ALEXANDER VALE DE ARAÚJO - PARNAMIRIM",
    ],

    RECONSTRUÇÃO: [
      "JOYCE JORDANA DA SILVA MEDEIROS - PARNAMIRIM",
      //"IZABELLA MOREIRA CORREA - PARNAMIRIM",
    ],
  },
} as const;